name: share settings

on:
  workflow_dispatch:
    inputs:
      species:
        type: choice
        options:
          - oak
          - cherry
          - maple
          - walnut

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      genus: ${{ steps.awk.outputs.genus }}
    steps:
      - name: fetch settings
        id: awk
        run: >
          curl -v
          -H 'Authorization: ${{ github.token }}'
          -H 'Accept: application/vnd.github.v3.raw'
          -L ${{ github.api_url }}/repos/${{ github.repository }}/contents/${{ github.ref_name }}/.github/workflows/shared.txt
          | awk '{ if ($1 == "${{ inputs.species }}") print "::set-output name=" $2 "::" $3 }'

  use:
    runs-on: ubuntu-latest
    needs: [info]
    env:
      GENUS: ${{ needs.info.outputs.genus }}
      
    steps:
      - name: report settings
        run: >
          echo ${{ inputs.species }} has genus: $GENUS
