# This is a basic workflow to help you get started with Actions

name: explore mappings

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      person:
        type: chioce
        description: selected human
        options:
          leo: {name: "Leonardo", "job": "painter", "country", "us"}
          mia: {name: "Mia", "job": "engineer", "country", "ca"}
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "Hello ${{ github.event.inputs.person.name }}! How is ${{ github.event.inputs.person.country }}?"
