# This is a basic workflow to help you get started with Actions

name: explore mappings

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      #person:
      #  type: choice
      #  description: selected human
      #  options: # want this, but dictionaries don't work
      #    leo: {name: "Leonardo", "job": "painter", "country": "us"}
      #    mia: {name: "Mia", "job": "engineer", "country": "ca"}
      magic:
        type: choice
        description: magic human
        options: # this hack works, but requires nested json when invoking from CLI
          - '{name: "Leonardo", "job": "painter", "country": "us"}'
          - '{name: "Mia", "job": "engineer", "country": "ca"}'
      lookup: # this hack creates an env we don't really want...
        type: choice
        description:  lookup human
        options:
          - leo
          - mia
          
env:
  PERSONS: >-
    {
      "leo": { "name": "Leonardo", "job": "painter", "country": "us"},
      "mia": { "name": "Mia", "job": "engineer", "country": "ca"}
    }
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Run a single-line script
        run: echo $PERSONS
        
      - name: Run a multi-line script
          #echo "Hello ${{ fromJSON(github.event.inputs.person).name }}! How is ${{ fromJSON(github.event.inputs.person).country }}?"
          #echo "Hello ${{ fromJSON(github.event.inputs.person)[0] }}, ${{ fromJSON(github.event.inputs.person)[1].name }}! How is ${{ fromJSON(github.event.inputs.person)[1].country }}?"
        run: |
          echo "Hello ${{ fromJSON(github.event.inputs.magic).name }}! How is ${{ fromJSON(github.event.inputs.magic).country }}?"
          echo "Lookup ${{ github.event.inputs.lookup }}: ${{ fromJSON(env.PERSONS)[github.event.inputs.lookup].name }}! How is ${{ fromJSON(env.PERSONS)[github.event.inputs.lookup].country }}?"
