# This is a basic workflow to help you get started with Actions

name: explore mappings

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      person:
        type: choice
        description: selected human
        options:
          leo: {name: "Leonardo", "job": "painter", "country": "us"}
          mia: {name: "Mia", "job": "engineer", "country": "ca"}
      magic:
        type: choice
        description: selected human
        options:
          - '{name: "Leonardo", "job": "painter", "country": "us"}'
          - '{name: "Mia", "job": "engineer", "country": "ca"}'
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Hello ${{ fromJSON(github.event.inputs.person).name }}! How is ${{ fromJSON(github.event.inputs.person).country }}?"
          echo "Hello ${{ fromJSON(github.event.inputs.person)[0] }}, ${{ fromJSON(github.event.inputs.person)[1].name }}! How is ${{ fromJSON(github.event.inputs.person)[1].country }}?"
          echo "Hello ${{ fromJSON(github.event.inputs.magic).name }}! How is ${{ fromJSON(github.event.inputs.magic).country }}?"
